### ISSUE TITLE
请问作者执行gitbook build 的时候，怎么去除生成的.md后缀的文件的呢？

### ISSUE THREAD

**Issue by xianhenyuan** [JoeyBling/myBook#19]

**Comment by txt611** [comment]
比如我本地的 markdown 文件是在 part1/conten1.md ；在我执行 gitbook build 后，在我本地生成的 _book/part1 目录下，除了生成了可访问的 html 目录，还生成了 .md 后缀结尾的文件，这种情况我看您的 myBook 项目gh-pages 分支下并没有存在

**Comment by JoeyBling** [comment]
@xianhenyuan 你好，我使用```gitbook build```进行生成文件的时候没有出现过这种情况哦，是不是您哪里配置了的问题，或者是目录结构的问题

**Comment by txt611** [comment]
@JoeyBling 感谢您的回复，可能是我本地 gitbook 配置的问题。请问一下，您本地 CLI 和 gitbook 的版本是多少呢？

**Comment by JoeyBling** [comment]
@xianhenyuan 你可以参考下我的配置，看看是不是你哪里配置有问题
- 版本的话我要明天才能回复您，因为那台机器暂时不在身边，明天我登上去查一下版本号再回您

**Comment by txt611** [comment]
@JoeyBling 好的，给您添麻烦了

**Comment by JoeyBling** [comment]
@xianhenyuan 我本地 `CLI` 和 `gitbook` 的版本
- **CLI version: 2.3.2**
- **GitBook version: 3.2.3**

**Comment by JoeyBling** [comment]
@xianhenyuan 你可以使用 `gitbook build --gitbook=3.2.3`  生成时指定gitbook的版本, 本地没有会先下载

**Comment by txt611** [comment]
@JoeyBling 好的，非常感谢

**Comment by JoeyBling** [comment]
@xianhenyuan 没事，希望能帮到您！
